/*
 * ServerPanel.java
 *
 * Created on October 28, 2003, 10:53 AM
 */

package org.genepattern.gpge.ui.maindisplay;

/**
 *
 * @author  kohm
 */
public class ServerPanel extends javax.swing.JPanel {
    
    /** Creates new form ServerPanel */
    public ServerPanel() {
        this(-1);
    }
    /** Creates new form ServerPanel */
    public ServerPanel(final int n) {
        initComponents();
        this.index = n;
    }
    
    /** gets the index associated with this panel */
    public final int getIndex() {
        return index;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents

        setLayout(new java.awt.CardLayout());

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /** the index that this panel is associated with */
    private final int index;
}
