/*
 * DataObjectBrowser.java
 *
 * Created on February 17, 2003, 10:50 AM
 */

package org.genepattern.gpge.ui.maindisplay;

import javax.swing.JComponent;

/**
 * 
 * @author keith
 */
public class TreePanel extends javax.swing.JScrollPane {

	/**
	 * Creates new form DataObjectBrowser this constuctor is just for the GUI
	 * builders
	 * 
	 * @see DataObjectBrowser(String)
	 */
	public TreePanel() {
		this(new javax.swing.JTree());
	}

	/**
	 * Creates new form DataObjectBrowser this constuctor is just for the GUI
	 * builders
	 * 
	 * @see DataObjectBrowser(String)
	 */
	public TreePanel(final JComponent comp) {
		setViewportView(comp);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents
		setPreferredSize(new java.awt.Dimension(600, 200));
		setMinimumSize(new java.awt.Dimension(600, 200));

	}//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JTree obj_tree;
	// End of variables declaration//GEN-END:variables

}