/*
  The Broad Institute
  SOFTWARE COPYRIGHT NOTICE AGREEMENT
  This software and its documentation are copyright (2003-2006) by the
  Broad Institute/Massachusetts Institute of Technology. All rights are
  reserved.

  This software is supplied without any warranty or guaranteed support
  whatsoever. Neither the Broad Institute nor MIT can be responsible for its
  use, misuse, or functionality.
*/


/*
 * DropTargetTextField.java
 *
 * Created on March 24, 2003, 10:32 AM
 */

package org.genepattern.modules.ui.graphics;

/**
 * 
 * @author kohm
 */
public class DropTargetTextField extends javax.swing.JTextField {

	/** Creates new form DropTargetTextField */
	public DropTargetTextField() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents

		setLayout(new java.awt.BorderLayout());

	}//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

}