/*******************************************************************************
 * Copyright (c) 2003, 2015 Broad Institute, Inc. and Massachusetts Institute of Technology.  All rights reserved.
 *******************************************************************************/


/*
 * DropTargetTextField.java
 *
 * Created on March 24, 2003, 10:32 AM
 */

package org.genepattern.modules.ui.graphics;

/**
 * 
 * @author kohm
 */
public class DropTargetTextField extends javax.swing.JTextField {

	/** Creates new form DropTargetTextField */
	public DropTargetTextField() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {//GEN-BEGIN:initComponents

		setLayout(new java.awt.BorderLayout());

	}//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables

}
