#!/bin/csh

set PATH=$1;  setenv PATH

setenv LD_LIBRARY_PATH ${2}:$LD_LIBRARY_PATH

setenv XAPPLRESDIR ${3} 

#echo command line: ${argv}

# Pass remaining arguments to gp_gistic2_from_seg using ${argv[4-]}
${1}gp_gistic2_from_seg ${argv[4-]}

