#!/bin/bash

# Hack to get the working directory
DIR=$(cd "$(dirname "$0")"; pwd)

# If the flag is there indicating that configuration has already been ran
if [ -f "$DIR/../Resources/ready" ]
then
    # Launch GenePattern and open your browser pointing to it
    $DIR/../Resources/GenePatternServer/Tomcat/bin/catalina.sh run &
    sleep 3
    open http://127.0.0.1:8080/gp
else
    # Otherwise launch the config app
    java -cp "$DIR/../Resources/bootstrap.jar:$DIR/../Resources/mail.jar:$DIR/../Resources/jgoodies-forms-1.9.0.jar:$DIR/../Resources/jgoodies-common-1.8.1.jar" org.genepattern.startapp.Bootstrap $DIR
fi