#!/bin/bash
DIR=$(cd "$(dirname "$0")"; pwd)

if [ -f "$DIR/../Resources/ready" ]
then
    $DIR/../Resources/GenePatternServer/Tomcat/bin/catalina.sh run &
    sleep 3
    open http://127.0.0.1:8080/gp
else
    java -cp "$DIR/../Resources/bootstrap.jar:$DIR/../Resources/mail.jar:$DIR/../Resources/jgoodies-forms-1.9.0.jar:$DIR/../Resources/jgoodies-common-1.8.1.jar" org.genepattern.startapp.Bootstrap $DIR
    #$DIR/../Resources/GenePatternServer/Tomcat/bin/catalina.sh run &
    #sleep 3
    #open http://127.0.0.1:8080/gp
fi