#!/bin/bash

# Ensure that the correct version of java is installed
if type -p java; then
    echo found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo found java executable in JAVA_HOME
    _java="$JAVA_HOME/bin/java"
else
    osascript -e 'tell app "System Events" to display dialog "Java 7+ required to run GenePattern. Please install Java."'
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo version "$version"
    if [[ "$version" > "1.7" ]]; then
        echo "Version of Java passes inspection."
    else
        osascript -e 'tell app "System Events" to display dialog "Java 7+ required to run GenePattern. Please install a newer version of Java."'
    fi
fi

# Get the 'GenePattern.app' directory
APP_DIR=$(cd "$(dirname "$0")"; cd ../; cd ../; pwd)
export GENEPATTERN_APP_DIR="$APP_DIR"

# Get the working directory
DIR=$(cd "$(dirname "$0")"; pwd)

# Set the GENEPATTERN_HOME_DIR
export GENEPATTERN_HOME=${HOME}/.genepattern

# If the flag is there indicating that configuration has already been ran
if [ -f "${APP_DIR}/Contents/Resources/ready" ]
then
    # Launch GenePattern and open your browser pointing to it
    "${GENEPATTERN_APP_DIR}/Contents/Resources/GenePatternServer/Tomcat/bin/catalina-macapp.sh" run &
    sleep 3
    open http://127.0.0.1:8080/gp
else
    echo "launching config app..."
    # Otherwise launch the config app
    java -cp "${APP_DIR}/Contents/Resources/bootstrap.jar:${APP_DIR}/Contents/Resources/javax.mail.jar:${APP_DIR}/Contents/Resources/jgoodies-forms-1.9.0.jar:${APP_DIR}/Contents/Resources/jgoodies-common-1.8.1.jar" org.genepattern.startapp.GenePattern "${DIR}"
fi
