
/* JOB STATUS CODE TABLE */

CREATE TABLE GPPORTAL.JOB_STATUS 
(
  STATUS_ID NUMBER(10,0) NOT NULL, 
  STATUS_NAME VARCHAR2(20 CHAR), 
  PRIMARY KEY (STATUS_ID)
);


/* TASK ACCESS CODE TABLE */

CREATE TABLE GPPORTAL.TASK_ACCESS
(
  ACCESS_ID    NUMBER(10,0) NOT NULL,
  NAME         VARCHAR2(4000),
  DESCRIPTION  VARCHAR2(4000), 
  PRIMARY KEY (ACCESS_ID)
);


/* TASK MASTER TABLE */
CREATE TABLE GPPORTAL.TASK_MASTER 
(
  TASK_ID NUMBER(10,0) NOT NULL, 
  TASK_NAME VARCHAR2(4000 CHAR), 
  DESCRIPTION VARCHAR2(4000 CHAR), 
  PARAMETER_INFO VARCHAR2(4000 CHAR),  
  TYPE_ID NUMBER(10,0), 
  REPEAT_MINUTE VARCHAR2(4000 CHAR), 
  REPEAT_HOUR VARCHAR2(4000 CHAR), 
  REPEAT_DAY_OF_MONTH VARCHAR2(4000 CHAR), 
  REPEAT_MONTH_OF_YEAR VARCHAR2(4000 CHAR), 
  REPEAT_DAY_OF_WEEK VARCHAR2(4000 CHAR), 
  TASKINFOATTRIBUTES VARCHAR2(4000 CHAR), 
  USER_ID VARCHAR2(4000 CHAR), 
  ACCESS_ID NUMBER(10,0), 
  LSID VARCHAR2(4000 CHAR), 
  PRIMARY KEY (TASK_ID)
);


ALTER TABLE GPPORTAL.TASK_MASTER
 ADD FOREIGN KEY (ACCESS_ID) 
 REFERENCES GPPORTAL.TASK_ACCESS (ACCESS_ID);

CREATE INDEX IDX_USER_ID ON TASK_MASTER (USER_ID);
CREATE INDEX IDX_ACCESS_ID ON TASK_MASTER (ACCESS_ID);
CREATE INDEX IDX_TASK_NAME ON TASK_MASTER (TASK_NAME);
CREATE INDEX IDX_LSID ON GPPORTAL.TASK_MASTER (LSID);


CREATE SEQUENCE GPPORTAL.TASK_MASTER_SEQ
  START WITH 1000
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;




/* ANALYSIS JOB */

CREATE TABLE GPPORTAL.ANALYSIS_JOB 
(
  JOB_NO          NUMBER(10,0) NOT NULL,  
  TASK_ID         NUMBER(10,0),  
  STATUS_ID       NUMBER(10,0),
  DATE_SUBMITTED  TIMESTAMP,
  DATE_COMPLETED  TIMESTAMP,
  PARAMETER_INFO  VARCHAR2(4000),
  USER_ID         VARCHAR2(4000),
  ISINDEXED       NUMBER(1,0) DEFAULT 0 NOT NULL,
  ACCESS_ID       NUMBER(10,0),
  JOB_NAME        VARCHAR2(4000),
  LSID            VARCHAR2(4000),
  TASK_LSID       VARCHAR2(4000),
  TASK_NAME       VARCHAR2(4000),
  PARENT          NUMBER(10,0),
  DELETED         NUMBER(1,0) DEFAULT 0 NOT NULL,
  PRIMARY KEY (JOB_NO)
);

ALTER TABLE GPPORTAL.ANALYSIS_JOB
 ADD FOREIGN KEY (STATUS_ID) 
 REFERENCES GPPORTAL.JOB_STATUS (STATUS_ID);
 
ALTER TABLE GPPORTAL.ANALYSIS_JOB
 ADD FOREIGN KEY (TASK_ID) 
 REFERENCES GPPORTAL.TASK_MASTER (TASK_ID);
 
ALTER TABLE GPPORTAL.ANALYSIS_JOB
 ADD FOREIGN KEY (ACCESS_ID) 
 REFERENCES GPPORTAL.TASK_ACCESS (ACCESS_ID);

CREATE SEQUENCE GPPORTAL.ANALYSIS_JOB_SEQ
  START WITH 1000
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;



/* SUITE TABLE  */
CREATE TABLE GPPORTAL.SUITE 
(
  SUITE_ID NUMBER(10,0) NOT NULL, 
  LSID VARCHAR2(4000 CHAR), 
  NAME VARCHAR2(4000 CHAR), 
  AUTHOR VARCHAR2(4000 CHAR), 
  OWNER VARCHAR2(4000 CHAR), 
  DESCRIPTION VARCHAR2(4000 CHAR), 
  ACCESS_ID NUMBER(10,0), 
  PRIMARY KEY (SUITE_ID)
);

/* SUITE MODULES */

CREATE TABLE GPPORTAL.SUITE_MODULES 
(
  MODULE_ID NUMBER(10,0) NOT NULL, 
  LSID VARCHAR2(255 CHAR), 
  MODULE_LSID VARCHAR2(255 CHAR), 
  PRIMARY KEY (MODULE_ID)
);


/* LSIDS */
CREATE TABLE GPPORTAL.LSIDS 
(
  LSID VARCHAR2(255 CHAR) NOT NULL, 
  LSID_NO_VERSION VARCHAR2(255 CHAR), 
  LSID_VERSION VARCHAR2(255 CHAR), 
  PRIMARY KEY (LSID)
);

CREATE INDEX IDX_LSID_VERSION ON GPPORTAL.LSIDS (LSID_VERSION);

CREATE INDEX IDX_LSID_NO_VERSION ON GPPORTAL.LSIDS (LSID_NO_VERSION);


/* PROPERTY TABLE */
CREATE TABLE GPPORTAL.PROPS 
(
  KEY VARCHAR2(100 CHAR) NOT NULL, 
  VALUE VARCHAR2(256 CHAR), 
  PRIMARY KEY (KEY)
);



CREATE SEQUENCE GPPORTAL.LSID_IDENTIFIER_SEQ START WITH 1;

CREATE SEQUENCE GPPORTAL.LSID_SUITE_IDENTIFIER_SEQ  START WITH 1;


INSERT INTO GPPORTAL.JOB_STATUS VALUES(1,'Pending');
INSERT INTO GPPORTAL.JOB_STATUS VALUES(2,'Processing');
INSERT INTO GPPORTAL.JOB_STATUS VALUES(3,'Finished');
INSERT INTO GPPORTAL.JOB_STATUS VALUES(4,'Error');

INSERT INTO GPPORTAL.TASK_ACCESS VALUES(1,'public','public access');
INSERT INTO GPPORTAL.TASK_ACCESS VALUES(2,'private','access only for the owner');

INSERT INTO GPPORTAL.PROPS (KEY, VALUE) VALUES ('schemaVersion', '2.1.0');








