
/* JOB STATUS CODE TABLE */

CREATE TABLE JOB_STATUS 
(
  STATUS_ID NUMBER(10,0) NOT NULL, 
  STATUS_NAME VARCHAR2(20 CHAR), 
  PRIMARY KEY (STATUS_ID)
);


/* TASK ACCESS CODE TABLE */

CREATE TABLE TASK_ACCESS
(
  ACCESS_ID    NUMBER(10,0) NOT NULL,
  NAME         VARCHAR2(4000),
  DESCRIPTION  VARCHAR2(4000), 
  PRIMARY KEY (ACCESS_ID)
);


/* TASK MASTER TABLE */
CREATE TABLE TASK_MASTER 
(
  TASK_ID NUMBER(10,0) NOT NULL, 
  TASK_NAME VARCHAR2(4000 CHAR), 
  DESCRIPTION VARCHAR2(4000 CHAR), 
  TYPE_ID NUMBER(10,0), 
  REPEAT_MINUTE VARCHAR2(4000 CHAR), 
  REPEAT_HOUR VARCHAR2(4000 CHAR), 
  REPEAT_DAY_OF_MONTH VARCHAR2(4000 CHAR), 
  REPEAT_MONTH_OF_YEAR VARCHAR2(4000 CHAR), 
  REPEAT_DAY_OF_WEEK VARCHAR2(4000 CHAR), 
  USER_ID VARCHAR2(4000 CHAR), 
  ACCESS_ID NUMBER(10,0), 
  LSID VARCHAR2(4000 CHAR),
  ISINDEXED NUMBER(1,0) DEFAULT 0 NOT NULL, 
  TASKINFOATTRIBUTES CLOB, 
  PARAMETER_INFO CLOB,  
  PRIMARY KEY (TASK_ID)
);


CREATE INDEX IDX_USER_ID ON TASK_MASTER (USER_ID);
CREATE INDEX IDX_ACCESS_ID ON TASK_MASTER (ACCESS_ID);
CREATE INDEX IDX_TASK_NAME ON TASK_MASTER (TASK_NAME);
CREATE INDEX IDX_LSID ON TASK_MASTER (LSID);


CREATE SEQUENCE TASK_MASTER_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;




/* ANALYSIS JOB */

CREATE TABLE ANALYSIS_JOB 
(
  JOB_NO          NUMBER(10,0) NOT NULL,  
  TASK_ID         NUMBER(10,0),  
  STATUS_ID       NUMBER(10,0),
  DATE_SUBMITTED  TIMESTAMP,
  DATE_COMPLETED  TIMESTAMP,
  USER_ID         VARCHAR2(4000),
  ISINDEXED       NUMBER(1,0) DEFAULT 0 NOT NULL,
  ACCESS_ID       NUMBER(10,0),
  JOB_NAME        VARCHAR2(4000),
  LSID            VARCHAR2(4000),
  TASK_LSID       VARCHAR2(4000),
  TASK_NAME       VARCHAR2(4000),
  PARENT          NUMBER(10,0),
  DELETED         NUMBER(1,0) DEFAULT 0 NOT NULL,
  PARAMETER_INFO  CLOB,
  PRIMARY KEY (JOB_NO)
);

CREATE SEQUENCE ANALYSIS_JOB_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;



/* SUITE TABLE  */
CREATE TABLE SUITE 
(
  SUITE_ID NUMBER(10,0) NOT NULL, 
  LSID VARCHAR2(4000 CHAR), 
  NAME VARCHAR2(4000 CHAR), 
  AUTHOR VARCHAR2(4000 CHAR), 
  OWNER VARCHAR2(4000 CHAR), 
  DESCRIPTION VARCHAR2(4000 CHAR), 
  ACCESS_ID NUMBER(10,0), 
  PRIMARY KEY (SUITE_ID)
);


CREATE SEQUENCE SUITE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;


/* SUITE MODULES */

CREATE TABLE SUITE_MODULES 
(
  MODULE_ID NUMBER(10,0) NOT NULL, 
  LSID VARCHAR2(255 CHAR), 
  MODULE_LSID VARCHAR2(255 CHAR), 
  PRIMARY KEY (MODULE_ID)
);

CREATE SEQUENCE SUITE_MODULES_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

/* LSIDS */
CREATE TABLE LSIDS 
(
  LSID VARCHAR2(255 CHAR) NOT NULL, 
  LSID_NO_VERSION VARCHAR2(255 CHAR), 
  LSID_VERSION VARCHAR2(255 CHAR), 
  PRIMARY KEY (LSID)
);

CREATE INDEX IDX_LSID_VERSION ON LSIDS (LSID_VERSION);

CREATE INDEX IDX_LSID_NO_VERSION ON LSIDS (LSID_NO_VERSION);



/* SEQUENCE TABLES FOR LSIDS */

CREATE TABLE SEQUENCE_TABLE 
(
  ID NUMBER(10,0) NOT NULL, 
  NAME VARCHAR2(100 CHAR) NOT NULL UNIQUE, 
  NEXT_VALUE NUMBER(10,0) NOT NULL, 
  PRIMARY KEY (ID)
);


/* PROPERTY TABLE */
CREATE TABLE PROPS 
(
  KEY VARCHAR2(100 CHAR) NOT NULL, 
  VALUE VARCHAR2(256 CHAR), 
  PRIMARY KEY (KEY)
);


/* USER TABLE */

CREATE TABLE GP_USER
(
  ID         NUMBER(10) OT NULL,
  USERNAME           VARCHAR2(255 CHAR),
  PASSWORD        VARCHAR2(255 CHAR),
  EMAIL              VARCHAR2(255 CHAR),
  LAST_LOGIN_DATE    TIMESTAMP(6),
  LAST_LOGIN_IP      VARCHAR2(255 BYTE),
  TOTAL_LOGIN_COUNT  INTEGER  DEFAULT 0  NOT NULL,
  PRIMARY KEY (ID)
);




CREATE SEQUENCE GP_USER_SEQ
  START WITH 0
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;














