create table job_comment (
 id bigint generated by default as identity (start with 1),
 gp_job_no integer not null,
 comment_text varchar(1023) not null,
 parent_id bigint,
 posted_date timestamp not null,
 user_id varchar(255) not null,
 primary key (id),
 CONSTRAINT fk_gp_job_no
    FOREIGN KEY (gp_job_no)
    REFERENCES analysis_job (job_no)
    ON DELETE CASCADE
);

create table tag (
 id integer generated by default as identity (start with 1),
 date timestamp not null,
 public_tag bit not null,
 tag varchar(511) not null,
 user_id varchar(255) not null,
 primary key (id)
);

create table job_tag (
 id integer generated by default as identity (start with 1),
 date timestamp not null,
 gp_job_no integer not null,
 tag_id integer not nul,
 user_id varchar(255) not null,
 primary key (id),
 CONSTRAINT jt_fk_gp_job_no
    FOREIGN KEY (gp_job_no)
    REFERENCES analysis_job (job_no)
    ON DELETE CASCADE
);

create index idx_comment_text on job_comment(comment_text);

create index idx_tag on tag(tag);

-- update schema version
update props set value='3.9.1' where key='schemaVersion';
