-- update schema version
update props set value='3.5.1' where key='schemaVersion';

create table job_input (
    id bigint generated by default as identity (start with 1), 
    job_id integer,
    name varchar(511),
    user_value varchar(4000), 
    cmd_value varchar(4000),  
    kind varchar(255),  
    primary key (id),
    unique (job_id, name)
);
create index idx_job_input_job_id on job_input (job_id);

create table job_input_attribute (
    id bigint generated by default as identity (start with 1), 
    input_id bigint,
    name varchar(255),
    val varchar(4000), 
    primary key (id)
);
create index idx_job_input_attribute_input_id on job_input_attribute (input_id);