create table PIN_MODULE (
	id integer generated by default as identity (start with 1),
    user varchar(511),
    lsid varchar(511),
    index double,
    primary key (id)
);
create index idx_pin_module on PIN_MODULE (id);

-- update schema version
insert into PROPS (KEY, VALUE) VALUES ('registeredVersion3.7.5', '3.7.5');

commit;

