create table job_comment (
 id bigint generated by default as identity (start with 1),
 gp_job_no integer not null,
 comment_text varchar(1023) not null,
 parent_id bigint,
 posted_date timestamp not null,
 user_id varchar(255) not null,
 primary key (id)
);

create index idx_comment_text on job_comment(comment_text);

-- update schema version
update props set value='3.9.1' where key='schemaVersion';
