
/* Job Status code table */

CREATE TABLE GPPORTAL.JOB_STATUS 
(
  STATUS_ID NUMBER(10,0) NOT NULL, 
  STATUS_NAME VARCHAR2(20 CHAR), 
  PRIMARY KEY (STATUS_ID)
);


/* Task Access code table */

CREATE TABLE GPPORTAL.TASK_ACCESS
(
  ACCESS_ID    NUMBER(10,0) NOT NULL,
  NAME         VARCHAR2(4000),
  DESCRIPTION  VARCHAR2(4000), 
  PRIMARY KEY (ACCESS_ID)
);


/* Task Master table */
CREATE TABLE GPPORTAL.TASK_MASTER 
(
  TASK_ID NUMBER(10,0) NOT NULL, 
  TASK_NAME VARCHAR2(4000 CHAR), 
  DESCRIPTION VARCHAR2(4000 CHAR), 
  PARAMETER_INFO VARCHAR2(4000 CHAR),  
  TYPE_ID NUMBER(10,0), 
  REPEAT_MINUTE VARCHAR2(4000 CHAR), 
  REPEAT_HOUR VARCHAR2(4000 CHAR), 
  REPEAT_DAY_OF_MONTH VARCHAR2(4000 CHAR), 
  REPEAT_MONTH_OF_YEAR VARCHAR2(4000 CHAR), 
  REPEAT_DAY_OF_WEEK VARCHAR2(4000 CHAR), 
  TASKINFOATTRIBUTES VARCHAR2(4000 CHAR), 
  USER_ID VARCHAR2(4000 CHAR), 
  ACCESS_ID NUMBER(10,0), 
  LSID VARCHAR2(4000 CHAR), 
  PRIMARY KEY (TASK_ID)
);


ALTER TABLE GPPORTAL.TASK_MASTER
 ADD FOREIGN KEY (ACCESS_ID) 
 REFERENCES GPPORTAL.TASK_ACCESS (ACCESS_ID);

CREATE INDEX IDX_USER_ID ON TASK_MASTER (USER_ID);
CREATE INDEX IDX_ACCESS_ID ON TASK_MASTER (ACCESS_ID);
CREATE INDEX IDX_TASK_NAME ON TASK_MASTER (TASK_NAME);
create index idx_lsid on gpportal.TASK_MASTER (LSID);


CREATE SEQUENCE GPPORTAL.TASK_MASTER_SEQ
  START WITH 1000
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;




/* Analysis Job */

CREATE TABLE GPPORTAL.ANALYSIS_JOB 
(
  JOB_NO          NUMBER(10,0) NOT NULL,  
  TASK_ID         NUMBER(10,0),  
  STATUS_ID       NUMBER(10,0),
  DATE_SUBMITTED  TIMESTAMP,
  DATE_COMPLETED  TIMESTAMP,
  PARAMETER_INFO  VARCHAR2(4000),
  USER_ID         VARCHAR2(4000),
  ISINDEXED       NUMBER(1,0) DEFAULT 0 NOT NULL,
  ACCESS_ID       NUMBER(10,0),
  JOB_NAME        VARCHAR2(4000),
  LSID            VARCHAR2(4000),
  TASK_LSID       VARCHAR2(4000),
  TASK_NAME       VARCHAR2(4000),
  PARENT          NUMBER(10,0),
  DELETED         NUMBER(1,0) DEFAULT 0 NOT NULL,
  PRIMARY KEY (JOB_NO)
);

ALTER TABLE GPPORTAL.ANALYSIS_JOB
 ADD FOREIGN KEY (STATUS_ID) 
 REFERENCES GPPORTAL.JOB_STATUS (STATUS_ID);
 
ALTER TABLE GPPORTAL.ANALYSIS_JOB
 ADD FOREIGN KEY (TASK_ID) 
 REFERENCES GPPORTAL.TASK_MASTER (TASK_ID);
 
ALTER TABLE GPPORTAL.ANALYSIS_JOB
 ADD FOREIGN KEY (ACCESS_ID) 
 REFERENCES GPPORTAL.TASK_ACCESS (ACCESS_ID);

CREATE SEQUENCE GPPORTAL.ANALYSIS_JOB_SEQ
  START WITH 1000
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;



/* Suite table  */
CREATE TABLE GPPORTAL.SUITE 
(
  LSID VARCHAR2(4000 CHAR) NOT NULL, 
  NAME VARCHAR2(4000 CHAR), 
  AUTHOR VARCHAR2(4000 CHAR), 
  OWNER VARCHAR2(4000 CHAR), 
  DESCRIPTION VARCHAR2(4000 CHAR), 
  ACCESS_ID NUMBER(10,0), 
  PRIMARY KEY (LSID)
);


/* Suite modules */

CREATE TABLE GPPORTAL.SUITE_MODULES
(
  LSID         VARCHAR2(4000 BYTE),
  MODULE_LSID  VARCHAR2(4000 BYTE)
);


/* Lsids */
CREATE TABLE GPPORTAL.LSIDS 
(
  LSID VARCHAR2(255 CHAR) NOT NULL, 
  LSID_NO_VERSION VARCHAR2(255 CHAR), 
  LSID_VERSION VARCHAR2(255 CHAR), 
  PRIMARY KEY (LSID)
);

create index idx_lsid_version on gpportal.LSIDS (LSID_VERSION);

create index idx_lsid_no_version on gpportal.LSIDS (LSID_NO_VERSION);


/* Property table */

CREATE TABLE GPPORTAL.PROPS
(
  KEY        VARCHAR2(4000)   NOT NULL,
  VALUE      VARCHAR2(4000)   NOT NULL
);


CREATE SEQUENCE GPPORTAL.lsid_identifier_seq START WITH 1;

CREATE SEQUENCE GPPORTAL.lsid_suite_identifier_seq  START WITH 1;


insert into GPPORTAL.job_status values(1,'Pending');
insert into GPPORTAL.job_status values(2,'Processing');
insert into GPPORTAL.job_status values(3,'Finished');
insert into GPPORTAL.job_status values(4,'Error');

insert into GPPORTAL.task_access values(1,'public','public access');
insert into GPPORTAL.task_access values(2,'private','access only for the owner');

INSERT INTO GPPORTAL.PROPS (KEY, VALUE) values ('schemaVersion', '2.1.0');








