



INSERT INTO GPPORTAL.SEQUENCE_TABLE (ID, NAME, NEXT_VALUE) 
  VALUES(1, 'lsid_identifier_seq',  1);
  

INSERT INTO GPPORTAL.SEQUENCE_TABLE (ID, NAME, NEXT_VALUE) 
  VALUES(2, 'lsid_suite_identifier_seq',  1);
  

INSERT INTO GPPORTAL.JOB_STATUS VALUES(1,'Pending');
INSERT INTO GPPORTAL.JOB_STATUS VALUES(2,'Processing');
INSERT INTO GPPORTAL.JOB_STATUS VALUES(3,'Finished');
INSERT INTO GPPORTAL.JOB_STATUS VALUES(4,'Error');

INSERT INTO GPPORTAL.TASK_ACCESS VALUES(1,'public','public access');
INSERT INTO GPPORTAL.TASK_ACCESS VALUES(2,'private','access only for the owner');

INSERT INTO GPPORTAL.PROPS (KEY, VALUE) VALUES ('schemaVersion', '2.1.0');

COMMIT;









