ALTER TABLE PUBLIC.SUITE ADD SUITE_ID INT IDENTITY;

ALTER TABLE PUBLIC.SUITE_MODULES ADD MODULE_ID INT IDENTITY PRIMARY KEY;

CREATE TABLE SEQUENCE_TABLE 
(
  ID INTEGER NOT NULL, 
  NAME VARCHAR(100) NOT NULL, 
  NEXT_VALUE INTEGER NOT NULL, 
  PRIMARY KEY (ID), 
  UNIQUE (NAME), 
  UNIQUE (ID)
);


INSERT INTO SEQUENCE_TABLE (ID, NAME, NEXT_VALUE) 
  VALUES(1, 'lsid_identifier_seq',  SELECT NEXT VALUE FOR LSID_IDENTIFIER_SEQ FROM DUAL);
  

INSERT INTO SEQUENCE_TABLE (ID, NAME, NEXT_VALUE) 
  VALUES(2, 'lsid_suite_identifier_seq',  SELECT NEXT VALUE FOR LSID_SUITE_IDENTIFIER_SEQ FROM DUAL);
  