CREATE TABLE BATCH_JOB (
    JOB_NO NUMBER(10,0) NOT NULL,
    USER_ID varchar2 (255),
    DELETED NUMBER(1,0) DEFAULT 0 NOT NULL,
    DATE_SUBMITTED TIMESTAMP,
    CONSTRAINT BJ_PK PRIMARY KEY (JOB_NO),
    CONSTRAINT BJ_FK FOREIGN KEY (USER_ID) 
        REFERENCES GP_USER ( USER_ID )
);

CREATE TABLE BATCH_ANALYSIS (
    BATCH_JOB NUMBER(10,0) NOT NULL,
    ANALYSIS_JOB NUMBER(10,0) NOT NULL,
    CONSTRAINT BA_BJ_FK foreign key (BATCH_JOB) references BATCH_JOB(JOB_NO) on delete cascade,
    constraint BA_AJ_FK foreign key (ANALYSIS_JOB) references ANALYSIS_JOB(JOB_NO) on delete cascade
);

CREATE SEQUENCE BATCH_JOB_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

-- update schema version
INSERT INTO PROPS (KEY, VALUE) VALUES ('registeredVersion3.3.0', '3.3.0');

COMMIT;
