/*
 * PropertyViewerPanel.java
 *
 * Created on April 23, 2003, 11:26 PM
 */

package org.genepattern.gpge.ui.propertyviewer;

import java.util.Iterator;
import java.util.Properties;
import java.util.Set;
import java.util.TreeSet;


import javax.swing.table.DefaultTableModel;
import javax.swing.CellEditor;

/**
 * Displays the all the properties in a Properties object.  Can be made editable
 * so the values of poperties can be changed.
 *
 * @author  keith
 */
public class PropertyViewerPanel extends javax.swing.JPanel {
    
    /** Creates new form PropertyViewerPanel */
    public PropertyViewerPanel() {
        initComponents();
    }
    /** creates a new PropertyViewerPanel loaded with the properties */
    public PropertyViewerPanel(final Properties props, final boolean editable) {
        this();
        jTable1.setModel(new PropertiesTableModel(props, editable));
    }
    
    /** stops cell editing and accepts any partial value */
    public final void stopCellEditing() {
        final CellEditor editor = jTable1.getCellEditor();
        if( editor != null )
            editor.stopCellEditing();
    }
//    /** test it */
//    public static final void main(final String[] args) {
//        javax.swing.JFrame frame = new javax.swing.JFrame("System properties");
//        final PropertyViewerPanel viewer = new PropertyViewerPanel(System.getProperties(), false);
//        frame.getContentPane().add(viewer);
//        frame.pack();
//        frame.show();
//        frame.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
//    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Property", "Value"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
//    /** the properties that are represented */
//    private Properties properties;
}
