CREATE TABLE "JOB_LSF" 
   (    "INTERNAL_JOB_ID" int NOT NULL, 
    "WORKING_DIRECTORY" VARCHAR(512), 
    "INPUT_FILENAME" VARCHAR(512), 
    "OUTPUT_FILENAME" VARCHAR(512), 
    "ERROR_FILENAME" VARCHAR(512), 
    "JOB_NAME" VARCHAR(512), 
    "QUEUE" VARCHAR(512), 
    "PROJECT" VARCHAR(512), 
    "LSF_JOB_STATUS" VARCHAR(255), 
    "LSF_JOB_ID" VARCHAR(255), 
    "STANDARD_OUTPUT" LONGVARCHAR, 
    "ERROR_OUTPUT" LONGVARCHAR, 
    "LISTENER_CLASS_NAME" VARCHAR(256), 
    "GAP_SERVER_ID" VARCHAR(256) NOT NULL, 
    "COMMAND" LONGVARCHAR, 
    "UPDATED_DATE" DATE, 
     CONSTRAINT "CK_JOB_LSF_COMMAND" CHECK (command IS NOT NULL), 
     PRIMARY KEY ("INTERNAL_JOB_ID") , 
     UNIQUE ("LSF_JOB_ID")
   ) ;
   
-- the following extra steps were required to set up the sequence for Hibernate with HSQL
CREATE TABLE dual_SQ_LSF_JOB (zero integer);
INSERT INTO dual_SQ_LSF_JOB values (0);
CREATE sequence SQ_LSF_JOB start with 1;
