/*
 * PredictionResultsViewer.java
 *
 * Created on February 12, 2003, 2:49 PM
 */

package org.genepattern.modules.ui.odfviewer;

import org.genepattern.data.FeaturesetProperties;

/**
 * Generic viewer for any type of FeaturesetProperties object.
 * This could be subclassed to display certain FeaturesetProperties Model types
 * with a richer GUI.
 * @author  kohm
 */
public class DataPropertiesViewer extends javax.swing.JPanel {
    
    /** Creates new form PredictionResultsViewer */
    public DataPropertiesViewer() {
        initComponents();
    }
    /** Creates new form PredictionResultsViewer */
    public DataPropertiesViewer(final FeaturesetProperties props) {
        this();
        setFeaturesetProperties(props);
    }
    
    /** sets the FeaturesetProperties to display */
    public void setFeaturesetProperties(final FeaturesetProperties props) {
        //this.attributes_viewer.setAttributes(props.getAttributes());
        this.attributes_viewer.setAttributes(props);
        this.data_table.setModel(props);
    }
    public static final void main(final String[] args) throws Exception {
        java.io.FileInputStream in = new java.io.FileInputStream(args[0]);
        FeaturesetProperties fs = (FeaturesetProperties) new org.genepattern.io.parsers.FeaturesetPropertiesParser().parse(in, "Test");
        javax.swing.JFrame frame = new javax.swing.JFrame();
        frame.getContentPane().add(new DataPropertiesViewer(fs));
        frame.pack();
        frame.show();
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        attributes_viewer = new org.genepattern.modules.ui.odfviewer.AttributesViewer();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new org.genepattern.modules.ui.odfviewer.DataPropertiesTable();

        setLayout(new java.awt.BorderLayout());

        add(attributes_viewer, java.awt.BorderLayout.NORTH);

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(data_table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.genepattern.modules.ui.odfviewer.AttributesViewer attributes_viewer;
    private org.genepattern.modules.ui.odfviewer.DataPropertiesTable data_table;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
