/*
 * DataPropertiesTable.java
 *
 * Created on February 12, 2003, 2:55 PM
 */

package org.genepattern.modules.ui.odfviewer;

/**
 *
 * @author  kohm
 */
public class DataPropertiesTable extends org.genepattern.modules.ui.graphics.LegendTable {
    
    /** Creates new form DataPropertiesTable */
    public DataPropertiesTable() {
        super();
        initComponents();
    }
    
    /** Creates a new instance of DataPropertiesTable */
    public DataPropertiesTable(final org.genepattern.data.FeaturesetProperties model) {
        //super(model); //doesn't work
        this();
        setModel(model);
    }
    
    /**
     * Creates default cell renderers for objects, numbers, doubles, dates,
     * booleans, and icons.
     * @see javax.swing.table.DefaultTableCellRenderer
     *
     */
    protected void createDefaultRenderers() {
        super.createDefaultRenderers();
        // primitives
        setLazyRenderer(java.lang.Byte.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        setLazyRenderer(java.lang.Short.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        setLazyRenderer(java.lang.Integer.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        setLazyRenderer(java.lang.Long.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        
        setLazyRenderer(java.lang.Boolean.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        
        setLazyRenderer(java.lang.Character.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        
        setLazyRenderer(java.lang.Float.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        setLazyRenderer(java.lang.Double.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        
        
//        setLazyRenderer(java.lang.TYPE, "javax.swing.table.DefaultTableCellRenderer");
//        setLazyRenderer(java.lang.TYPE, "javax.swing.table.DefaultTableCellRenderer");
        
        
    }
    private void setLazyValue(java.util.Hashtable h, Class c, String s) {
	h.put(c, new javax.swing.UIDefaults.ProxyLazyValue(s));
    }

    private void setLazyRenderer(Class c, String s) {
	setLazyValue(defaultRenderersByColumnClass, c, s);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
