-- drop unused tables from DB
--
-- Note: must do this as a manual step because I haven't had a
-- chance to test the Oracle equivalent of 'drop table if exists ...'
-- 
-- drop table job_input;
-- drop table job_input_attribute;
