
ALTER TABLE PUBLIC.SUITE_MODULES ADD ID INT IDENTITY PRIMARY KEY;

CREATE TABLE SEQUENCE_TABLE
(
  ID INTEGER NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  NEXT_VALUE INTEGER NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (NAME),
  UNIQUE (ID)
);


/* USER TABLE */

CREATE TABLE GP_USER
(
  USER_ID varchar(255),
  GP_PASSWORD binary(255),
  EMAIL varchar(255),
  LAST_LOGIN_DATE timestamp,
  LAST_LOGIN_IP varchar(255),
  TOTAL_LOGIN_COUNT INTEGER  DEFAULT 0  NOT NULL,
  PRIMARY KEY (USER_ID)
);

/* USER PROPERTIES (preferences) */
CREATE TABLE GP_USER_PROP
(
  ID integer generated by default as identity (start with 1),
  KEY varchar(255),
  VALUE varchar(255),
  GP_USER_ID varchar(255),
  foreign key (GP_USER_ID) references GP_USER(USER_ID),
  PRIMARY KEY (ID)
);


/* Event logging */
create table job_completion_event
(
  id integer generated by default as identity (start with 1),
  user_id varchar(255),
  type varchar(255),
  job_number integer,
  parent_job_number integer,
  task_lsid varchar(255),
  task_name varchar(255),
  completion_status varchar(255),
  completion_date date,
  elapsed_time bigint,
  primary key (id)
);


/* Index status on analysis job */
create index idx_analysis_job_status on analysis_job(status_id);

create index idx_gp_user_prop_key on gp_user_prop(key);

/* Add contact column to Suite */
alter table suite add user_id varchar(255);

update  suite set user_id = owner where user_id is null;


