/*******************************************************************************
 * Copyright (c) 2003, 2015 Broad Institute, Inc. and Massachusetts Institute of Technology.  All rights reserved.
 *******************************************************************************/
package org.genepattern.server;

import static org.junit.Assert.assertEquals;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.HashMap;

import org.genepattern.server.config.GpConfig;
import org.genepattern.util.GPConstants;
import org.genepattern.webservice.JobInfo;
import org.genepattern.webservice.ParameterInfo;
import org.genepattern.webservice.TaskInfo;
import org.genepattern.webservice.TaskInfoAttributes;
import org.junit.Before;
import org.junit.Test;

/**
 * junit tests for the JobInfoManager class.
 * @author pcarr
 *
 */
public class TestJobInfoManager {
    private GpConfig gpConfig;

    private static final String lsid="urn:lsid:broad.mit.edu:cancer.software.genepattern.module.visualizer:00261:999999999";
    private TaskInfoAttributes tia;
    private TaskInfo taskInfo;
    private HashMap<String, String> attrs;
    private ParameterInfo[] parameterInfos;
    private ParameterInfo pinfo;
    private JobInfo jobInfo;
    private final int jobNo=41;
    private final String userId="admin";

    @Before
    public void setUp() throws MalformedURLException {
        final URL gpUrl=new URL("http://127.0.0.1:8080/gp/");
        gpConfig=new GpConfig.Builder().genePatternURL(gpUrl).build();

        
        tia = new TaskInfoAttributes();
        tia.put(GPConstants.TASK_TYPE, GPConstants.TASK_TYPE_JAVASCRIPT);
        tia.put("commandLine", "clsfilecreator.html ? <input.file>");
        taskInfo=mock(TaskInfo.class);
        when(taskInfo.getLsid()).thenReturn(lsid);
        when(taskInfo.getTaskInfoAttributes()).thenReturn(tia);
        when(taskInfo.getAttributes()).thenReturn(tia);

        attrs=new HashMap<String, String>();
        attrs.put("default_value", "");
        attrs.put("optional", "");
        attrs.put("prefix_when_specified", "");
        attrs.put("MODE", "URL_IN");
        attrs.put("type", "java.io.File");
        attrs.put("fileFormat", "gct;res");
        
        pinfo=new ParameterInfo();
        pinfo.setName("input.file");
        pinfo.setAttributes(attrs);

        parameterInfos = new ParameterInfo[1];
        parameterInfos[0]=pinfo;
        
        jobInfo=mock(JobInfo.class);
        when(jobInfo.getJobNumber()).thenReturn(jobNo);
        when(jobInfo.getParameterInfoArray()).thenReturn(parameterInfos);
    }
    
    /*
     * Test cases, generated by scraping values at runtime from the debugger
     */
    
    
    @Test
    public void generateLaunchUrl_userUpload() throws Exception {
        pinfo.setValue("<GenePatternURL>users/admin/all_aml_test.gct");
        final String fileUrl="http://127.0.0.1:8080/gp/users/admin/all_aml_test.gct";
        assertEquals(
                // expected
                "http://127.0.0.1:8080/gp/tasklib/"+lsid+"/clsfilecreator.html?job.number="+jobNo+"&input.file="+fileUrl,
                // actual
                JobInfoManager.generateLaunchURL(gpConfig,taskInfo, jobInfo.getJobNumber())
                );
    }

    @Test
    public void generateLaunchUrl_jobUpload() throws Exception {
        pinfo.setValue("<GenePatternURL>users/"+userId+"/tmp/run8743873107529768988.tmp/input.file/1/all_aml_train.gct");
        final String fileUrl="http://127.0.0.1:8080/gp/users/"+userId+"/tmp/run8743873107529768988.tmp/input.file/1/all_aml_train.gct";
        assertEquals(
                // expected
                "http://127.0.0.1:8080/gp/tasklib/"+lsid+"/clsfilecreator.html?job.number="+jobNo+"&input.file="+fileUrl,
                // actual
                JobInfoManager.generateLaunchURL(gpConfig,taskInfo, jobInfo.getJobNumber())
                );
    }
    
    @Test
    public void generateLaunchUrl_externalUrl() throws Exception  {
        pinfo.setValue("http://www.broadinstitute.org/cancer/software/genepattern/data/all_aml/all_aml_train.gct");
        final String fileUrl="http://www.broadinstitute.org/cancer/software/genepattern/data/all_aml/all_aml_train.gct";
        assertEquals(
                // expected
                "http://127.0.0.1:8080/gp/tasklib/"+lsid+"/clsfilecreator.html?job.number="+jobNo+"&input.file="+fileUrl,
                // actual
                JobInfoManager.generateLaunchURL(gpConfig,taskInfo, jobInfo)
                );
    }

}
