# This is a basic workflow to help you get started with Actions

name: Trigger_docker_build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch.  For this one it needs a tag with a leading lowercase 'v'
# as we normally use for releases
on:
  push:
    tags: 
      - v*

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: genepattern/genepattern-server
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "send_dispatch_event"
  send_dispatch_event:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # not needed yet, but leaving in as its part of the template
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell, just as an example
    - name: Run a one-line script
      run: echo Hello, world!

    # multi-line scripts need the '|' on the first line
    # the ${{ github.ref }} in the payload will be the tag like so 'refs/tags/v0.23'
    # which the other side will use to look for an installer at 
    # https://github.com/genepattern/github-actions-testing/releases/download/v0.23/GPserver.bin
    # so it will strip the refs/tags at the destination 
    - name: sendEvent 
      run: |
        curl -XPOST -H "Accept: application/vnd.github.everest-preview+json" \
         --header 'authorization: Bearer ${{ secrets.teds_token }}' \
        -H "Content-Type: application/json" \
        https://api.github.com/repos/genepattern/github-actions-testing/dispatches \
        --data '{"event_type": "my-event", "client_payload": { "ref": "${{ github.ref }}", "ref2": "TED_DID_THIS" }}'
         
  build_and_push:
    # Ensure test job passes before pushing image.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Extract version
        id: vars
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.teds_dockerhub_token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.version }}
          build-args: |
            GP_INSTALLER=https://github.com/genepattern/genepattern-server/releases/download/${{ steps.vars.outputs.version }}/GPserver.bin
